language: cpp
sudo: true
dist: trusty
matrix:
   include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - pip install --user cpp-coveralls

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make && make test

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
